### ISSUE TITLE
Errors in replicating BipedalWalker: TypeError: reset() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by JundaHe** [Qi-Pang/MDPFuzz#1]
When replicating the code for the BipedalWalker game, I encountered the following error: 
```
Traceback (most recent call last):
  File "enjoy.py", line 311, in <module>
    main()
  File "enjoy.py", line 151, in main
    obs = env.reset(states)
TypeError: reset() takes 1 positional argument but 2 were given
```

I follow the instructions given to set up the environment and use the command `python enjoy.py --alg tqc --env BipedalWalkerHardcore-v3 --folder rl-trained-agents/ --em` to start fuzz testing

I notice that in the original implementation of gym, the reset function only takes 1 positional argument. The code is available [here](https://github.com/openai/gym/blob/0.19.0/gym/envs/box2d/bipedal_walker.py#L317). May I ask how could I solve this problem. Did you change the original implementation of BipedalWalker when running your experiments? Thank you very much

**Comment by Qi-Pang** [comment]
Hi, thanks a lot for the question and the reminder. Yes, we have modified the gym library to do the environment mutation. The current code is not cleaned and we will try to update the code to make it functional asap (within this month). Please keep tuned.

**Comment by JundaHe** [comment]
Thank you very much for the response, I am looking forward to your update! 

> Hi, thanks a lot for the question and the reminder. Yes, we have modified the gym library to do the environment mutation. The current code is not cleaned and we will try to update the code to make it functional asap (within this month). Please keep tuned.

**Comment by Qi-Pang** [comment]
Hi, I have updated the missing libraries. Hopefully, it's functional now. Let me know if it's still not working on your end.

**Comment by JundaHe** [comment]
> 

Hi Qi-Pang, Thank you very much for the update!
